insert into node(id, name) values (1, 'amsel');
insert into node(id, name) values (2, 'turdus');
insert into node(id, name) values (3, 'turdidae');
insert into node(id, name) values (4, 'passeri');
insert into node(id, name) values (5, 'passeriformes');
insert into node(id, name) values (6, 'aves');
insert into node(id, name) values (7, 'tetrapoda');
insert into node(id, name) values (8, 'gnathostomata');
insert into node(id, name) values (9, 'vertebrata');
insert into node(id, name) values (10, 'chordata');
insert into node(id, name) values (11, 'deuterostomina');
insert into node(id, name) values (12, 'bilateria');
insert into node(id, name) values (13, 'eumetazoa');
insert into node(id, name) values (14, 'metazoa');
insert into node(id, name) values (15, 'holozoa');
insert into node(id, name) values (16, 'eukaryonten');
insert into is_a(node1, node2) values (1, 2);
insert into is_a(node1, node2) values (2, 3);
insert into is_a(node1, node2) values (3, 4);
insert into is_a(node1, node2) values (4, 5);
insert into is_a(node1, node2) values (5, 6);
insert into is_a(node1, node2) values (6, 7);
insert into is_a(node1, node2) values (7, 8);
insert into is_a(node1, node2) values (8, 9);
insert into is_a(node1, node2) values (9, 10);
insert into is_a(node1, node2) values (10,11);
insert into is_a(node1, node2) values (11,12);
insert into is_a(node1, node2) values (12,13);
insert into is_a(node1, node2) values (13,14);
insert into is_a(node1, node2) values (14,15);
insert into is_a(node1, node2) values (15,16);

