version: "3.3"
services:
  main:
    image: tpires/neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - /home/ingo/development/java/Mindware/Semanticweb/docker/data:/var/lib/neo4j/data
    environment:
     - NEO4J_AUTH=ingo:ingo
    cap_add:
     - SYS_RESOURCE
    stdin_open: true
    tty: true
